# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real externally-driven piezo sounder (TDK PS1240P02BT), transcribed from
// the TDK PS-series catalog (007-01/20110508/ef532_ps; part detail catalog
// p.3, page-verified from rendered page images — the catalog has no text
// layer). Two PCB pins, 12.7mm pitch, body 12.2 x 6.5mm; 4kHz at 3 Vo-p
// rectangular wave, 70dBA/10cm min, max input 30 Vo-p (without DC bias).
// The catalog documents no polarity for the pin-terminal parts.
// Pins ride the mclibs passive piezo sounder shape.

use mclibs.audio/buzzer.mc

component BUZZER.PS1240P02BT : BUZZER.PIEZO
{
    partno = "PS1240P02BT"
    package = PKG.PIEZO_SOUNDER_D12_2

    // Catalog p.3, PS1240P02BT spec table (page-verified); dBA and Vo-p have
    // no unit entry in the mcc table, so the value rides bare and the unit
    // rides the description (LSb precedent, mcp4921)
    spec = [
        spl  = 70, "min sound pressure, dBA at 10cm, at 4kHz and 3 Vo-p rectangular wave (25°C pm 5, 60 pm 10 percent RH)"
        vin  = 30, "max input voltage, Vo-p rectangular, without DC bias"
        temp = -10°C ~ +70°C, "operating temperature range"
    ]
}
