# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real MCU (Unisound US513U61 voice SoC, QFN20; board marking US513_20_F (renamed US513U6 2026-10-03)),
// extracted verbatim from the verified hbl
// board (U192 mcu batch). Ruling U192-3: the MCU stays a standalone real
// part for now - no abstract base until an industry-naming abstract cluster
// is summarized later (mux branch pins are the part's private face).

component MCU.US513U6                                                  // MCU controller, QFN20
{
    partno = "US513U61"                                                   // Unisound Hummingbird-L voice SoC (board marking US513_20_F (renamed US513U6 2026-10-03))
    package = PKG.QFN20                                                   // QFN20 package

    pins = [                                                              // pin definitions
        io [1, 2] = I2C0::I2C(MASTER)                                     // pins 1 and 2 can be configured as the I2C interface
                    | GPIO[3, 4]::GPIO(PROVIDER)                        // or as GPIO

        in [3, 4] = XTAL::XTAL(OSCILLATOR)                                // 32K crystal input/output pins (oscillator side, carries the sustaining amplifier)
        psnk [5, 21] = [VDD, GND]::DC(3.3V)                               // VDD supply input, 3.3V (sink)
        io [6, 7] = UART0::UART.TTL(DCE)                                  // pins [6,7] can be configured as UART0 serial
                    | I2C1::I2C(MASTER)                                   // pins [6,7] can be configured as the I2C1 interface
                    | GPIO[5, 6]::GPIO(PROVIDER)                        // pins [6,7] can also be configured as GPIO

        io [8, 9] = PDM[CLK, DATA]
                    | PBus{CLK, DATA}
                    | GPIO[7, 8]::GPIO(PROVIDER)                        // pins [8,9] can be configured as the PDM interface, or as GPIO

        io [10, 11] = I2C1::I2C(MASTER) | GPIO[9, 10]::GPIO(PROVIDER),  // pins [10,11] can be configured as the I2C1 interface, or as GPIO
        ["I2C", "GPIO"], volt:1.2V, amp:100mA

        // Master wire order [SCLK, MOSI, MISO, CS] (b3804 face order), hence pin numbers [8, 9, 11, 10]
        io [8, 9, 11, 10] = SPI{SCLK, MOSI, MISO, CSN}::SPI(MASTER)       // pin 8=SCLK, 9=MOSI, 11=MISO, 10=CSN, written in Master wire order
        io [12, 13] = UART1::UART.TTL(DCE)                                // pins [12,13] can be configured as UART1 serial
                      | GPIO[5, 6]::GPIO(PROVIDER)                      // or as GPIO

        psnk [14, 21] = [VDD_CORE, GND]::DC(1.2V)                         // 1.2V supply input (sink)
        in 15 = AVDD09_CAP                                                // analog supply decoupling-capacitor input pin
        io [16, 17] = ADC::ADC.DIFF(RECEIVER) @class(analog)              // analog differential input interface P/N (ADC.DIFF has only the P/N pair)
        io [18, 19] = JTAG::DBG.JTAG.2(TAP)                               // pins 18 and 19 can be configured as the JTAG interface
                      | GPIO[0,1]::GPIO(PROVIDER)                       // or as GPIO
        // | I2S::I2S()                         // or as the I2S interface

        io 20 = GPIO[2] | EXT_CLK_IN                                      // pin 20 can be configured as GPIO, or as external clock input
    ]

    // Terminal-level parameterized wiring macro: external supply pair into the chip's
    // power pins, with entry decoupling hung on contact (standard chip-power paradigm):
    //   [external supply pair] -> [this.power pin pair] => CAP(...).Cap(_)
    // The right-hand pin pair must be qualified with this. as a whole pair (the formal
    // GND collides with the pin name GND; a collision statement must qualify the whole
    // pair - qualifying only the colliding member silently drops that member's
    // rail-to-pin merge row - locked by round_cases chip_power_paradigm).
    func Power([VDD_3V3, GND]::DC(3.3V), [VCC_1V2, GND]::DC(1.2V)) {
        [VDD_3V3, GND] -> [this.VDD, this.GND] => CAP(1uF, ±10%, CAP.X5R, 10V).Cap(_)    // 3.3V supply pair into pins + entry decoupling in one statement (paradigm)
        [VCC_1V2, GND] -> [this.VDD_CORE, this.GND] => CAP(1uF, ±10%, CAP.X5R, 10V).Cap(_)  // 1.2V, same paradigm
        CAP(1uF, ±10%, CAP.X5R, 10V).Cap([AVDD09_CAP, GND])             // AVDD09_CAP decoupling (analog reference decoupled to digital GND; single decoupling pin, not a supply pair, Set form)
    }

    func Address(address) {
        // The I2C0 address is selected by the level on GPIO.02: GPIO.02 high -> I2C0 address addr:0x36;
        // GPIO.02 low -> I2C0 address addr:0x35

        if address == 0x36
            RES(100kΩ).Pullup([GPIO[2], VDD])   // GPIO.02 pulled up to VDD_3V3 through a 100K resistor, setting GPIO.02 high
        else                               //if address == 0x35
            RES(100kΩ).Pulldown([GPIO[2], GND])   // GPIO.02 pulled down to GND through a 100K resistor

        // Each of the two I2C0 signal lines gets a pull-up resistor to VDD for signal integrity.
        RES(10kΩ).Pullup([I2C0.SCL, VDD])  // I2C0.SCL pulled up to VDD
        RES(10kΩ).Pullup([I2C0.SDA, VDD])  // I2C0.SDA pulled up to VDD
    }
}
