# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real 64-pin general-purpose MCU (ST STM32F205RET6, LQFP64 10x10),
// transcribed from the ST datasheet (DS6329 Rev 18; Figure 10 LQFP64
// pinout p.41 cross-checked pin by pin against the Table 5/6 LQFP64
// pin-definitions columns, 64/64 agree). Part number per the ordering
// scheme (R = 512KB flash, E = 512KB, T = LQFP, 6 = -40 to 85C).
// Standalone real part (ruling as us513u6): no LQFP64 abstract shape
// exists in mclibs yet -- summarize the cluster before basing.
//
// Pin names are the datasheet port names (PH0_OSC_IN / PH1_OSC_OUT per
// DS6329; some third-party boards label pins 5/6 "PD0/PD1", an F103
// carry-over -- the pin NUMBERS 5/6 agree everywhere). GPIO rows carry
// the board-facing alternate names only (USB/SWD); the full AF map is
// out of transcription scope. VCAP_1/VCAP_2 (pins 31/47) are the core
// regulator capacitor terminals -- each needs its own 2.2uF to GND,
// they are NOT extra VSS returns.

component MCU.STM32F205RET6                                                  // MCU controller, LQFP64
{
    partno = "STM32F205RET6"                                            // ST STM32F205RET6 (Cortex-M3, 512KB flash)
    package = PKG.LQFP64                                                // LQFP64 package

    spec = [
        vdd = 1.8V ~ 3.6V, "VDD/VDDA operating supply window"           // DS6329 Table 12, p.50 (VDDA>=VDD; with ADC in use VDDA 2.4V~3.6V)
        vbat = 1.65V ~ 3.6V, "VBAT operating window"                    // DS6329 Table 12, p.50
        freq = 120MHz, "CPU clock, max"                                 // DS6329 p.1 feature bullet
        temp = -40°C ~ +85°C, "operating temperature, suffix 6"         // DS6329 ordering scheme Table 3, p.19
    ]

    pins = [                                                            // pin definitions (LQFP64, pin numbers per DS6329 Figure 10, p.41)

        // -- power face (digital): VDD 19/32/48/64, returns VSS 18/63
        psnk [[19, 32, 48, 64], [18, 63]] = [VDD, VSS]::DC(3.3V)        // digital supply pair (sink)
        // -- power face (analog): VDDA 13, return VSSA 12 (VDDA >= VDD)
        psnk [13, 12] = [VDDA, VSSA]::DC(3.3V)                          // analog supply pair (sink)
        // -- battery-backup domain: VBAT 1 (tie to the same 3.3V rail as VDD when no backup battery is used)
        psnk [1, 18] = [VBAT, VSS]::DC(3.3V)                            // VBAT supply input (sink)
        // -- core regulator capacitor pins: each gets its own 2.2uF to GND (NOT extra supply returns!)
        in 31 = VCAP_1                                                  // core LDO capacitor pin 1 (external 2.2uF)
        in 47 = VCAP_2                                                  // core LDO capacitor pin 2 (external 2.2uF)

        // -- clock: main oscillator terminals (oscillator side, carries the sustaining
        //    amplifier); adopts the XTAL interface so the pairing-face ERC applies
        //    (RESONATOR pairs with exactly one OSCILLATOR); pin names still follow the datasheet
        in [5, 6] = XTAL::XTAL(OSCILLATOR), ["PH0_OSC_IN", "PH1_OSC_OUT"]  // main crystal input/output (some boards label them PD0/PD1-OSC, an F103 carry-over)
        io 7 = RST{NRST}::RST(RECEIVER)                                 // bidirectional system reset (active low; adopts the RST interface, reset-body side)
        in 60 = BOOT0                                                   // boot selection (weak pull-up/pull-down selects the boot region)

        // -- GPIOA (pin numbers per Figure 10)
        io 14 = PA0                                                     // WKUP/ADC12_IN0
        io 15 = PA1                                                     // ADC12_IN1
        io 16 = PA2                                                     // ADC12_IN2
        io 17 = PA3                                                     // ADC12_IN3
        io 20 = PA4                                                     // ADC12_IN4/SPI1_NSS
        io 21 = PA5                                                     // ADC12_IN5/SPI1_SCK
        io 22 = PA6                                                     // ADC12_IN6/SPI1_MISO
        io 23 = PA7                                                     // ADC12_IN7/SPI1_MOSI
        io 41 = PA8                                                     // USART1_CK/TIM1_CH1
        io 42 = PA9                                                     // USART1_TX/TIM1_CH2
        io 43 = PA10                                                    // USART1_RX/TIM1_CH3
        io 44 = PA11 | USB_DM                                           // CAN_RX/USB_DM/USART1_CTS
        io 45 = PA12 | USB_DP                                           // CAN_TX/USB_DP/USART1_RTS
        io 46 = PA13 | SWDIO | JTMS                                     // SWD data (FT pin)
        io 49 = PA14 | SWCLK | JTCK                                     // SWD clock (FT pin)
        io 50 = PA15                                                    // JTDI/SPI1_NSS

        // -- GPIOB
        io 26 = PB0                                                     // ADC12_IN8/TIM3_CH3
        io 27 = PB1                                                     // ADC12_IN9/TIM3_CH4
        io 28 = PB2                                                     // BOOT1/ADC12_IN12
        io 55 = PB3                                                     // JTDO/SPI1_SCK
        io 56 = PB4                                                     // NJTRST/SPI1_MISO
        io 57 = PB5                                                     // SPI1_MOSI/TIM3_CH2
        io 58 = PB6                                                     // I2C1_SCL/TIM4_CH1
        io 59 = PB7                                                     // I2C1_SDA/TIM4_CH2
        io 61 = PB8                                                     // CAN_RX/TIM4_CH3
        io 62 = PB9                                                     // CAN_TX/TIM4_CH4
        io 29 = PB10                                                    // I2C2_SCL/USART3_TX
        io 30 = PB11                                                    // I2C2_SDA/USART3_RX
        io 33 = PB12                                                    // SPI2_NSS/I2C2_SMBA
        io 34 = PB13                                                    // SPI2_SCK/USART3_CTS
        io 35 = PB14                                                    // SPI2_MISO/USART3_RTS
        io 36 = PB15                                                    // SPI2_MOSI/TIM1_CH3N

        // -- GPIOC
        io 8  = PC0                                                     // ADC123_IN10
        io 9  = PC1                                                     // ADC123_IN11
        io 10 = PC2                                                     // ADC123_IN12
        io 11 = PC3                                                     // ADC123_IN13
        io 24 = PC4                                                     // ADC12_IN14
        io 25 = PC5                                                     // ADC12_IN15
        io 37 = PC6                                                     // TIM3_CH1/I2S2_MCK
        io 38 = PC7                                                     // TIM3_CH2/USART6_RX
        io 39 = PC8                                                     // TIM3_CH3/USART6_TX
        io 40 = PC9                                                     // TIM3_CH4/USART6_RX
        io 51 = PC10                                                    // UART4_TX/SDIO_D2
        io 52 = PC11                                                    // UART4_RX/SDIO_D3
        io 53 = PC12                                                    // UART5_TX/SDIO_CK
        io 2  = PC13                                                    // RTC_AF1/TAMPER (RTC alternate function)
        io 3  = PC14                                                    // OSC32_IN (32K crystal alternate function)
        io 4  = PC15                                                    // OSC32_OUT (32K crystal alternate function)

        // -- GPIOD (only PD2 is brought out on the LQFP64)
        io 54 = PD2                                                     // UART5_RX/SDIO_CMD
    ]

    // -- typical-application wrappers (mcd checklist §6.9; extracted from the
    //    DS6329 typical application)

    // Block level: power/decoupling group. Digital and analog domains are passed
    // separately (boards that filter VDDA on a separate rail pass different domains);
    // VBAT follows the same-rail hookup (DS6329: tie to VDD when no backup battery is
    // used); battery-backup boards tie it to the battery instead.
    func Power([VDD_3V3, GND]::DC(3.3V), [VDDA_3V3, GND]::DC(3.3V)) {
        VDD_3V3 - VDD                                                   // digital supply sink 19/32/48/64
        GND - VSS                                                       // digital return sink 18/63
        VDDA_3V3 - VDDA                                                 // analog supply 13 (VDDA >= VDD)
        GND - VSSA                                                      // analog return 12
        VDD_3V3 - VBAT                                                  // VBAT same rail (pin 1)
        VCAP_1 - CAP(2.2uF, ±10%, CAP.X5R, 6.3V) - GND                  // core LDO capacitor 1 (DS6329: 2.2uF ceramic each)
        VCAP_2 - CAP(2.2uF, ±10%, CAP.X5R, 6.3V) - GND                  // core LDO capacitor 2
    }

    // Block level: reset RC. DS6329 typical: 0.1uF from NRST to ground (the internal
    // pull-up is built in; an external pull-up/reset button is a board-level choice
    // and stays out of this macro).
    func Reset(gnd) {
        RST.NRST - CAP(100nF, ±10%, CAP.X5R, 25V) - gnd                 // reset noise filter
    }
}

// Module-level wrapper (§6.9): minimum system = MCU + main crystal (with load
// capacitors) + reset RC + BOOT0 strap.
// The analog domain rides the same rail (boards that filter VDDA on a separate rail
// skip this module and call uC.Power with both domains themselves).
// BOOT0 pulled up 10k = boot from main flash (DS6329 BOOT value table; serial-
// bootloader boards tie it to ground instead).
module STM32F205_MINI(psnk pwr{V3V3, GND}::DC(3.3V), freq::UV.HZ, cload::UV.CAP)
{
    MCU.STM32F205RET6 uC
    .Power(pwr, pwr)                                                    // both domains on the same rail
    .Reset(pwr.GND)

    XTAL2(freq, cload) y1                                               // main crystal (mcode comp/xtal.mc)
    y1.Setup(pwr.GND) -> uC.XTAL{X1, X2}                                // load capacitors land on the crystal pins, ownership ruling U200
    uC.BOOT0 - RES(10kΩ, ±1%) - pwr.V3V3                                // main-flash-boot strap
}
