# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real LIN J2602 transceiver (MCP2003, 8-pin PDIP/SOIC; Microchip marks the
// part Not Recommended for New Designs in favor of MCP2003B -- kept as the
// industry-standard LIN pinout specimen), transcribed from DS20002230G
// (bullet specs p.1; pinout page-verified:
// 1 RXD, 2 CS, 3 WAKE, 4 TXD, 5 VSS, 6 LBUS, 7 VBB, 8 VREN).
// Pins ride the mclibs LIN transceiver shape.

use mclibs.comm/lin.mc

component XCVR.MCP2003 : XCVR.LIN
{
    partno = "MCP2003"
    package = PKG.SOIC8      // 8-pin PDIP / SOIC share one pinout (p.1);
                             // a 4x4 DFN body is also offered

    spec = [
        vbb = 6V ~ 27V, "continuous supply voltage"                   // p.1 bullet
        vloaddump = 43V, "load dump protected"                        // p.1 bullet
        rate = 20kbps, "max bus baud rate, LIN"                       // p.1 bullet: 20 Kbaud
        esd = 20kV, "ESD immunity on VBB, IEC 61000-4-2 (LBUS pm 14 kV)"  // p.1 bullet
        ipd = 5uA, "low-power mode current, receiver monitoring the bus"  // p.1 bullet
        temp = -40°C ~ +125°C, "extended operating temperature range" // p.1 bullet
    ]
}
