# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real analog audio power amplifier, extracted from the verified hbl board
// (U192, C7 electroacoustic batch). Pins ride the mclibs abstract shape.

use mclibs.analog/amp.mc

component AMP.LPA4871 : AMP.AUDIO_BTL
{
    partno = "LPA4871"
    package = PKG.SOP8
}
