#!/bin/bash
# Public-corpus face gate for mcpub. Checks the whole tree (it is small and
# grep-fast); any violation fails with exit 1 so the red set cannot grow.
#
# Laws enforced here (mcpub/CLAUDE.md):
#   1. English-only — every authored file (md/toml/mc/sh) is English; vendor
#      datasheet dumps (*.txt, *.pdf) are the manufacturer's own words and are
#      exempt.
#   2. Entry .mc provenance header — every entry .mc opens with the license
#      lines followed by the MCode Bench(TM) generated + third-party disclaimer
#      block.
#   3. pack.toml provenance header — same block, TOML-comment style, in front
#      of the manifest note.
#   4. Datasheet source link — every pack.toml carries the linked
#      `[[attachments]]` url field (empty string = placeholder, allowed).
#   5. No stale versioned artifact names in READMEs (use <name>-<version>).
set -u
cd "$(dirname "$0")"

fail=0

# -- 1. English-only ----------------------------------------------------------
cjk=$(grep -rlP '[\x{4e00}-\x{9fff}\x{3000}-\x{303f}\x{ff00}-\x{ffef}]' \
        --include='*.md' --include='*.toml' --include='*.mc' --include='*.sh' \
        . 2>/dev/null)
if [ -n "$cjk" ]; then
    echo "FAIL english-only (CJK found):"
    echo "$cjk" | sed 's/^/    /'
    fail=1
fi

# -- 2. entry .mc provenance header -------------------------------------------
for mc in */*/*.mc; do
    if ! grep -q "Generated by MCode Bench(TM). Transcribed from the manufacturer's public" "$mc" \
       || ! grep -q 'property of their respective third-party owners' "$mc" \
       || ! grep -q 'documentation before production use' "$mc"; then
        echo "FAIL provenance header missing: $mc"
        fail=1
    fi
done

# -- 3. pack.toml provenance header + datasheet source link -------------------
for toml in */*/pack.toml; do
    if ! grep -q "Generated by MCode Bench(TM). Transcribed from the manufacturer's public" "$toml" \
       || ! grep -q 'documentation before production use' "$toml"; then
        echo "FAIL provenance header missing: $toml"
        fail=1
    fi
    if ! grep -q '^url = ' "$toml"; then
        echo "FAIL datasheet source url missing: $toml"
        fail=1
    fi
done

# -- 4. no stale versioned artifact names in READMEs --------------------------
stale=$(grep -rn --include='README.md' -e '\-0\.1[0-9]*\.mcl' -e '~/.mcode/' . 2>/dev/null)
if [ -n "$stale" ]; then
    echo "FAIL stale artifact reference (use <name>-<version>.mcl):"
    echo "$stale" | sed 's/^/    /'
    fail=1
fi

if [ "$fail" -ne 0 ]; then
    echo "check.sh: FAILED"
    exit 1
fi
echo "check.sh: ok"
