// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  GC11N65D5 — 650V NMOS, DFN 5x6
//  No DFN5x6 member exists in the PKG enum, so `package` is left unset rather
//  than forced to a wrong value.
// =============================================================================
component NMOS.GC11N65
{
    partno = "GC11N65D5"

    pins = [
        io 1 = G
        io 2 = D
        io 3 = S
    ]
}
