// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  10D471 metal-oxide varistor (across L-N on the source board).
//  Pack name follows the part number, lowercased; digit-leading `use` segments
//  are accepted by the mcode parser.
// =============================================================================
component VARISTOR.MOV
{
    partno = "10D471"

    pins = [
        io 1 = 1
        io 2 = 2
    ]
}
