# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS
# IS, without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real character LCD module (Newhaven Display NHD-0216K1Z-NSW-BBW-L:
// 16x2 STN blue negative, transmissive, side white LED backlight),
// transcribed from the Newhaven product specification rev 11
// (nhd0216.pdf in this directory; pin table p.4, electrical
// characteristics p.5, controller information p.5).
// Page-verified faces: pin table p.4 (16 pads: VSS VDD V0 RS R/W E
// DB0..DB7 LED+ LED-; the mechanical drawing p.3 names pads 15/16 A/K);
// electrical p.5 (VDD 4.5/5.0/5.5V, IDD 0.5/1.0/2.0 mA, contrast node
// 3.6/3.7/3.8V at VDD=5V, top -20..+70 degC; backlight VLED 4.9..5.1V,
// ILED 10/32/40 mA via on-board resistor); controller p.5 = ST7066U
// (HD44780-equivalent), 1/16 duty / 1/5 bias, 4/8-bit bus per the
// Function-set DL bit. Sheet note: the printed p.5 symbol column is
// shifted one row (H-in labeled V_IL etc.) -- the values are the
// trustworthy part.
// The suffix letters are not decoded anywhere in the document; the
// part number below is the sheet's own cover title.

use mclibs.display/lcd.mc

component LCD.NHD0216K1ZNSWBBWL : LCD.CHR
{
    partno = "NHD-0216K1Z-NSW-BBW-L"
    package = PKG.LCD16X2     // 80.0 x 36.0 mm module, 13.5mm max depth, 16-pin 2.54mm single row (DS p.3 mechanical drawing)

    spec = [
        vdd = 4.5V ~ 5.5V, "logic supply (5.0V nominal)"                                        // p.5
        idd = 1mA, "supply current typ at 25C (0.5 ~ 2.0 mA min/max)"                           // p.5
        v0 = 3.7V, "contrast node nominal at VDD=5.0V (3.6 ~ 3.8V; approx 1.3V below VDD)"      // p.4/p.5
        temp = -20°C ~ +70°C, "operating temperature (storage -30 ~ +80°C)"                     // p.5
        vled = 4.9V ~ 5.1V, "backlight supply window (on-board series resistor)"                // p.5
        iled = 32mA, "backlight current typ (10 ~ 40 mA min/max)"                               // p.5
        controller = "ST7066U", "HD44780-equivalent controller, 1/16 duty / 1/5 bias"           // p.5
        lines = "16x2", "two lines x 16 characters; DDRAM line1 0x00-0x0F, line2 0x40-0x4F"     // p.5
    ]
}
