// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  FS8611B — FastSOC Type-C PD controller, SSOP10
//  Datasheet: FS8611B V1.x (bundled). No SSOP10 member exists in the PKG
//  enum, so `package` is left unset rather than forced to a wrong value.
// =============================================================================
component PDCTL.FS8611B
{
    partno = "FS8611B"

    pins = [
        psnk [1, 10] = [VIN, VSS]::DC(5V~20V)   // supply pair: 1 = VIN (PDISxN
                                        //   domain via R28 1K + C23 + Z4 clamp),
                                        //   10 = VSS return
        out 2 = CGATE                   // drives the external PMOS gate
        io 3 = FUNC1                    // repurposed as I2C SCL on this board (R44 pull-up to V3V3)
        io 4 = DP                       // Type-C D+ (A6/B6)
        io 5 = DM                       // Type-C D- (A7/B7)
        io 6 = CC1
        io 7 = CC2
        io 8 = FUNC2                    // repurposed as I2C SDA on this board (R43 pull-up to V3V3)
        io 9 = FB                       // regulation feedback (into the buck FB divider node)
    ]
}
