# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real 2-pin passive crystal (DST310S, 3215 package), extracted verbatim
// from the verified hbl board (U192 crystal batch).
//
// Ruling U192-2 keeps the parameterized crystal face in mcode (XTAL2(freq,
// cload) already carries it; concrete values flow through the formals).
// This file stays a standalone real part: a `:` binding against an mcode/
// mclibs abstract waits for the U187 xtal naming-law debt to clear first
// (bind-after-debt order, U192 table).

component CRYST.DST310S   // 2-pin passive crystal
{
    partno = "DST310S"       // part number is DST310S
    package = PKG.XTAL_3215  // 3215 package, i.e. 3.2mm x 2.5mm
    spec = [
        frequency = 32kHz    // crystal frequency is 32kHz
    ]

    pins = [
        [1, 2] = XTAL::XTAL(RESONATOR)  // pins 1 and 2 map to X1/X2 of the XTAL crystal interface (passive resonator side)
    ]

    func Setup(gnd) {
        XTAL - R442::RES(1MΩ, ±1%)'  // a 1MΩ resistor, ±1% tolerance, R0402 size, default NC (not fitted), instance named R442, in parallel with the crystal
        - [                          // series resonator capacitors 18pF, ±5%, 50V rating, C0402 size, default NC (not fitted)
            CAP(18pF, ±5%, CAP.C0G, 50V),
            CAP(18pF, ±5%, CAP.C0G, 50V)
        ]
        - [gnd, gnd]                 // series to the return
    }
}
