// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  JMUP jumper (0.6mm pitch, 2 pins). On the source board: J1 in series with
//  the LLC output to VBUS; J2's both pins tied to VSS.
// =============================================================================
component CONN.JMUP2
{
    partno = "JMUP-0.6mm"

    pins = [
        io 1 = 1
        io 2 = 2
    ]
}
