# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real low-cost I2C RTCC (MCP7940M, Microchip DS20002292C), rewritten from
// the datasheet. Pins are the verified device face (pin function table 2-1,
// shared by all five 8-lead packages): 1 X1, 2 X2, 3 NC, 4 VSS, 5 SDA,
// 6 SCL, 7 MFP, 8 VCC. The TDFN exposed pad ties to VSS or floats.
//
// The M member has NO battery backup: an earlier revision of this book
// carried the MCP7940N description (battery backup, power-fail time-stamp,
// backup voltage range) — that text belongs to the N and is dropped.
//
// The MFP row keeps a plain `out`: @drive is witnessed on interface pin rows
// only, and the open-drain note stays in the row description (lm66100 ST
// precedent).

use $::mcode.ifs

component SYS.Clock.MCP7940M(partno)
{
    description = "Low-Cost I2C Real-Time Clock/Calendar with 64-byte SRAM.
            Tracks hours, minutes, seconds, day of week, day, month and year,
            leap year compensated to 2399, 12/24 hour modes, dual programmable
            alarms, on-chip digital trimming (±1 PPM resolution, ±129 PPM
            range), and an open-drain multifunction output (alarm, selectable
            square wave, or general purpose output). I2C up to 400 kHz.
            Runs a 32.768 kHz tuning fork crystal with external load
            capacitors; optimized for 6-9 pF load capacitance crystals."

    // Ordering codes (datasheet section 10.1); T suffix = tape and reel.
    if (partno == "MCP7940M-I/SN") package = PKG.SOIC8
    else if (partno == "MCP7940MT-I/SN") package = PKG.SOIC8
    else if (partno == "MCP7940M-I/MS") package = PKG.MSOP8
    else if (partno == "MCP7940M-I/ST") package = PKG.TSSOP8
    else if (partno == "MCP7940MT-I/ST") package = PKG.TSSOP8
    else if (partno == "MCP7940MT-I/MNY") package = PKG.TDFN8_2X3
    else if (partno == "MCP7940M-I/P") package = PKG.DIP8
    else package = PKG.SOIC8

    spec = [
        vcc_req = 1.8V ~ 5.5V              // operating supply window
        workingtemperature = -40°C ~ +85°C // industrial (I) temperature range
        xtal_freq = 32.768kHz              // crystal class: CL 6-9 pF
    ]

    pins = [
        psnk [8,4] = [VCC,VSS]::DC()    // primary power supply / ground

        in [1,2] = XTAL{X1,X2}::XTAL(OSCILLATOR), ["Crystal X1", "Crystal X2"]
                                        // the device hosts the sustaining
                                        // amplifier; X1 doubles as the external
                                        // clock input (external-oscillator mode)

        io [5,6] = I2C{SDA,SCL}::I2C(SLAVE), ["I2C data", "I2C clock"]

        out 7 = MFP, "multifunction open-drain output (alarm / square wave / GPIO), pull up to VCC"

        nc 3 = NC
    ]

    // Standard chip-power paradigm: external supply pair into the power pins,
    // with entry decoupling hung on contact (one statement = Power+Cap)
    func Power([VCC, GND]::DC())
    {
        [VCC, GND] -> [this.VCC, this.VSS] => CAP(100nF).Cap(_)
    }

    func Xtal(gnd)
    {
        // Load capacitors are owned by the crystal setup (U200 ruling).
        XTAL2(32.768kHz, 7pF).Setup(gnd) -> [XTAL.X1, XTAL.X2]
    }
}
