# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

# PL3085A cn.ireader-opto

use mclibs.comm/uart2rs485.mc

component XCVR.PL3085A : XCVR.RS485
{
    name = "PL3085A"
    description = "UART/RS485 Tranciever"

    partno = "PL3085A"
    package = PKG.SOIC8

    spec.HBM = ±15kV
    spec.workingtemperature = -40°C ~ +85°C
}

module PL3085A_RS485(psnk pwr::DC(5V))
{
    in UART{TX, RX}
    out RS485{A, B}

    XCVR.PL3085A PL3085(pwr)
    pwr.VCC - CAP(100nF,10V) - pwr.GND
    DIO.TVS(13.3V, 19.9V, 600W) tvs_a
    tvs_a.Protect(PL3085.RS485.A, pwr.GND) //SMBJ12CA (VBR min 13.3V, VC 19.9V @ IPP, 600W)
    DIO.TVS(13.3V, 19.9V, 600W) tvs_b
    tvs_b.Protect(PL3085.RS485.B, pwr.GND) //SMBJ12CA (VBR min 13.3V, VC 19.9V @ IPP, 600W)
    PL3085.BiasMatch().AutoDirection()

    UART -> PL3085{UART | RS485} -> RS485
}
