// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  NCE30P28Q — PMOS, DFN 3.3x3.3 (vendor prefix NCE = NCE Power)
//  Symbol pinout: 1=G 2=S 3=D.
// =============================================================================
component PMOS.NCE30P28Q
{
    partno = "NCE30P28Q"
    package = PKG.DFN8_3X3

    pins = [
        io 1 = G
        io 2 = S
        io 3 = D
    ]
}
