// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  TEA1995T — NXP GreenChip dual-channel synchronous rectifier controller, SO8
//  Datasheet: TEA1995T Rev3 (bundled)
// =============================================================================
component SR.TEA1995T
{
    partno = "TEA1995T"
    package = PKG.SOIC8

    pins = [
        out 1 = GDA                     // channel A gate drive (T1 winding A, 16-17)
        io 3 = DSB                      // channel B drain sense (R31 <- Q8.DB)
        io 4 = SSB                      // channel B source sense (grounded)
        io 5 = SSA                      // channel A source sense (grounded)
        io 6 = DSA                      // channel A drain sense (R19 <- Q8.DA)
        psnk [7, 2] = [VCC, GND]::DC(12V)   // supply pair: 7 = VCC (VBUS domain,
                                        //   C20 decoupling), 2 = GND return
        out 8 = GDB                     // channel B gate drive (T1 winding B, 11-12)
    ]
}
