# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real two-channel RS232 line driver/receiver (MAX3232, 16-pin SOIC/SSOP/
// TSSOP/PDIP), transcribed from TI SLLS410O (bullet specs p.1; recommended
// operating conditions p.4; pinout page-verified: DOUT/DIN/RIN/ROUT spellings
// per the TI face, 1 C1+, 2 V+, 3 C1-, 4 C2+, 5 C2-, 6 V-, 15 GND, 16 VCC).
// Pins ride the mclibs RS232 transceiver shape.

use mclibs.comm/rs232.mc

component XCVR.MAX3232 : XCVR.RS232
{
    partno = "MAX3232"
    package = PKG.SOIC16    // 16-pin SOIC (D) / SSOP (DB) / SOIC (DW) /
                            // TSSOP (PW) / PDIP share one pinout (p.1 Device
                            // Information); the SOIC-16 body is stated first

    spec = [
        vdd = 3V ~ 5.5V, "single-supply operating voltage"        // p.1 bullet
        rate = 250kbps, "max data signaling rate"                 // p.1 bullet; Section 6.7: 250 kbit/s
        esd = 15kV, "RS-232 bus-terminal ESD (pm 15 kV), HBM"     // p.1 bullet
        icc = 300uA, "supply current, typ"                        // p.1 bullet
        slew = 30V/us, "driver output slew rate, max"             // p.1 Description
        temp = -40°C ~ +85°C, "operating free-air temperature, I grade (C grade 0°C ~ +70°C)"  // p.4 Section 6.3: MAX3232I / MAX3232C
    ]
}
