// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  FS116D — FastSOC multi-protocol Type-A quick-charge controller, SSOP10
//  Datasheet: FS116D V1.1 202410 (bundled)
// =============================================================================
component PDQC.FS116D
{
    partno = "FS116D"

    pins = [
        out 1 = GATE                    // external PMOS (Q15) gate drive
        psnk [2, 6] = [VIN, GND]::DC(5V~20V)    // supply pair: 2 = VIN (QCIS1N
                                        //   domain via R107 750R + C73 + Z6 clamp),
                                        //   6 = GND return
        io 3 = FUNC                     // QCPER plug-in indication (R104 pull-up to V3V3, R105 NC)
        io 4 = FB                       // regulation feedback (merged into the U8 FB node)
        io 5 = PLUGIN                   // floating on the schematic (no LED fitted) — legal
        in 7 = CSN                      // sense - (after the R70 10mOhm shunt, VSS domain here)
        io 8 = CSP                      // sense + (USB1.- via R106 300R + C90)
        io 9 = DP
        io 10 = DM
    ]
}
