// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  INN650D02 — GaN HEMT, DFN 8x8
//  No DFN8x8 member exists in the PKG enum, so `package` is left unset rather
//  than forced to a wrong value.
// =============================================================================
component NMOS.INN650D02
{
    partno = "INN650D02"

    pins = [
        io 1 = G
        io 2 = D
        io 3 = S
    ]
}
