# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real adjustable eFuse (TI TPS25200, SLVSCJ0F, March 2014 - Revised
// July 2025), transcribed from the page-verified sheet (tps25200.pdf in
// this directory; TI lit symlink direct hit).
// Page-verified faces: pinout Table 4-1 p.3 -- WSON-6 (DRV) 2x2mm, 1 OUT,
// 2 ILIM, 3 FAULT (active-low open-drain), 4 EN (active high, must not
// float), 5 GND (external to PowerPAD), 6 IN, PowerPAD internally GND;
// current limit programmable 85mA ~ 2.9A via single R_ILIM p.1/p.4 §5.5
// (Table: 33k -> 2952mA typ, 150k -> 647mA typ); overvoltage clamp
// 5.25/5.4/5.55 V p.5; OVLO rising 7.6 V typ p.5; FAULT asserts on
// overcurrent/overvoltage/overtemperature, 8ms typ OC deglitch, not
// asserted during clamp p.12; rDS(on) 60mΩ typ p.4; UL 2367 recognized p.1.
// Pins adopt the mclibs EFUSE family shape (adjustable-limit eFuse form);
// pad numbering here is the datasheet's own (the family was distilled
// from this part).

use mclibs.power/efuse.mc

component EFUSE.TPS25200 : EFUSE
{
    partno = "TPS25200"
    package = PKG.WSON6_2X2     // TI DRV: WSON-6, 2.0 x 2.0 mm, PowerPAD to GND (p.3, p.4 thermal)

    spec = [
        vin = 2.5V ~ 6.5V, "recommended input range (withstands 20 V transient)"   // p.4, p.3
        iout = 2.6A, "max continuous output current"                                // p.4
        ilim = 85mA ~ 2.9A, "current-limit program window via R_ILIM 33kΩ~1100kΩ"   // p.1, p.4
        ovc = 5.25V ~ 5.55V, "fixed overvoltage clamp V(OVC) min/typ/max"           // p.5
        ovlo = 7.6V, "overvoltage shutoff rising V(OVLO) typ (70mV hysteresis)"     // p.5
        ron = 60mΩ, "on-resistance typ at 25°C"                                     // p.4
        iin_off = 5µA, "supply current, disabled, max"                              // p.5
        temp = -40°C ~ +125°C, "recommended junction temperature range"             // p.4
    ]
}
