# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real dual full-bridge driver (L298N, Multiwatt15), transcribed from the
// ST L298 datasheet (p.2 PIN CONNECTIONS drawing; pinout page-verified,
// Pin Functions table p.3 cross-checked pin-by-pin). The metal tab is
// connected to pin 8 (GND). Vs abs max 46V (42V in characteristics),
// Vss 5V logic supply.
// Pins ride the mclibs classic dual full-bridge shape.

use mclibs.motor/hbridge.mc

component L298N : HBRIDGE.DUAL.E
{
    partno = "L298N"
}
