# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real single-digit 7-segment display (Kingbright SA03-11EWA: 7.62mm /
// 0.30 inch, high-efficiency red GaAsP/GaP, common anode, right-hand
// decimal, gray face white segment), transcribed from the Kingbright
// spec DSAP8320 rev V.1A (sa0311.pdf in this directory; internal-circuit
// pin map p.1, electrical/optical p.2).
// Page-verified faces: pin map p.1 read off the internal-circuit figure
// (a=1, f=2, common anode=3+14, e=7, d=8, DP2=9, c=10, g=11, b=13;
// pin 6 N/C; pins 4, 5, 12 molded off); selection guide p.1 (common
// anode, right-hand decimal, Iv 3600/8100 ucd min/typ @10mA); p.2 (VF
// 1.9V typ / 2.3V max at IF=10mA, lambda_dom 617nm typ / peak 627nm,
// IR <= 10uA at VR=5V, DC IF 30mA and peak IFM 160mA at 1/10 duty
// 0.1ms, top -40..+85 degC, 75mW, ESD 8kV HBM); through-hole 2.54mm
// pitch, wave-solder only (p.3).

use mclibs.display/seg7.mc

component SEG7.SA0311EWA : SEG7.CA
{
    partno = "SA03-11EWA"
    package = PKG.DIP10       // 10-pin through-hole 2.54mm pitch, 7.6mm digit height (DS p.1/p.3 outline)

    spec = [
        vf = 2.3V, "segment forward voltage max at IF=10mA (1.9V typ)"                          // p.2
        ifwd = 10mA, "test current for VF / Iv ratings (one series resistor per segment)"       // p.2
        ifmax = 30mA, "DC forward current absolute max (peak 160mA at 1/10 duty, 0.1ms)"        // p.2
        vr = 5V, "reverse voltage absolute max (IR <= 10 uA)"                                   // p.2
        wavelength = 617nm, "dominant wavelength typ (peak 627nm, high-efficiency red)"         // p.2
        iv = 8100, "luminous intensity ucd typ @10mA, min 3600 (CIE 127-2007 traceable)"        // p.1
        temp = -40°C ~ +85°C, "operating temperature (75mW power dissipation, ESD 8kV HBM)"     // p.2
    ]
}
