// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  MMBT4403 — PNP bipolar transistor, SOT-23
//  Symbol pinout: 1=B 2=E 3=C.
// =============================================================================
component PNP.MMBT4403
{
    partno = "MMBT4403"
    package = PKG.SOT_23

    pins = [
        io 1 = B
        io 2 = E
        io 3 = C
    ]
}
