// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  2N7002 — small-signal NMOS, SOT-23
//  1=G 2=D 3=S.
// =============================================================================
component NMOS.2N7002
{
    partno = "2N7002"
    package = PKG.SOT_23

    pins = [
        io 1 = G
        io 2 = D
        io 3 = S
    ]
}
