# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real three-phase gate driver with integrated buck regulator (DRV8302,
// DCA: 56-pin HTSSOP with PowerPAD numbered 57 = GND), transcribed from TI
// ZHCS138C (Chinese datasheet, p.3 package drawing; pinout page-verified,
// Pin Functions table cross-checked against the figure pin-by-pin).
// Two supply domains: PVDD1 (gate driver) and PVDD2 (buck). The exposed
// PowerPAD carries pin number 57 and the name GND.
// PVDD operating range 8-60V.
// Pins ride the mclibs three-phase gate driver with buck shape.

use mclibs.motor/gatedrv.mc

component GATEDRV.DRV8302 : GATEDRV.H6B
{
    partno = "DRV8302DCAR"
}
