// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  WRLSB80M — SMD bridge rectifier: 1/2 = AC, 3 = +, 4 = -.
// =============================================================================
component BRIDGE.WRLSB80M
{
    partno = "WRLSB80M"

    pins = [
        psrc [1, 2] = [AC1, AC2]        // AC inputs (1=LF1.4, 2=MAINS)
        io 3 = DCP                      // DC +
        in 4 = DCN                      // DC - (PGND)
    ]
}
