# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real electret capsule microphone, extracted from the verified hbl board
// (U192, C7 electroacoustic batch). Pins ride the mclibs abstract shape.

use mclibs.audio/microphone.mc

component MICROPHONE.SIP2_1_25MM_WA : MICROPHONE.ELECTRET
{
    partno = "CMC-6027-32T"       // CUI Devices / Same Sky electret capsule
    package = PKG.MIC_SIP2
}
