# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real dual-channel digital isolator (TI ISO7721 series, detail model
// ISO7721D: SOIC-8 (D) plastic package, channel A reversed, outputs
// default HIGH), transcribed from the TI "ISO772x High-Speed, Robust EMC,
// Reinforced and Basic Dual-Channel Digital Isolators" sheet (iso7721.pdf
// in this directory; SLLSEP3G, November 2016 - Revised May 2024; TI lit
// symlink direct hit -- no mirror workaround needed).
// Page-verified faces: pinout Table 5-1 p.6 (1 VCC1, 2 OUTA, 3 INB,
// 4 GND1, 5 GND2, 6 OUTB, 7 INA, 8 VCC2 for the ISO7721 D/DWV footprint);
// function Table 8-2 p.25 (open input or VCC1 powered down -> output
// assumes the default; VCCO powered down -> output undetermined);
// insulation §6.6 p.10 and isolation Table 6-? p.11 for the D-8 package
// values; electrical characteristics p.14 (5 V tables).
// The F-suffix siblings (ISO7721FD/ISO7721FDR, p.38) share this footprint
// with outputs default LOW -- a spec-row difference, not a shape
// difference, so they are orderable variants of this same body.

use mclibs.isolation/iso_dig.mc

component ISO7721D : ISO.DIG2.REVA
{
    partno = "ISO7721D"
    package = PKG.SOIC8         // D-8: 4.90 x 3.91 mm body, 1.75 mm max height (mechanical drawing p.34)

    spec = [
        data_rate = 100Mbps, "max signaling rate (higher rates possible, p.8 footnote 3)"          // p.8, p.24
        prop_delay = 11ns, "typ propagation delay at 5 V (max 17 ns); pulse distortion 5.9 ns max"  // p.1, p.17
        cmti = 100kV/us, "typ common-mode transient immunity (min 85 kV/us), VCM = 1200 V"          // p.14
        supply = 2.25V~5.5V, "recommended VCC1/VCC2, independently settable; UVLO falling 1.7 V"    // p.8, p.25
        iso_rating = 3kV, "UL 1577 withstand, D-8 package (1 s production test at 1.2 x VISO)" // p.11, p.12
        viorm = 450V, "max repetitive peak isolation voltage, D-8 (637 VPK / 637 VDC)"           // p.10
        surge = 10kV, "VIOSM surge immunity, D-8 (1.2/50 us, IEC 62368-1)"                      // p.10
        default_output = "high", "outputs default HIGH (open input / VCC1 down; no F suffix)"         // p.1, p.24, p.25
        creepage = 4mm, "creepage = clearance = 4 mm, DTI 17 um, material group I, CTI > 600 V"     // p.10
        temp = -55°C ~ +125°C, "orderable operating range"                                          // pp.37-38
    ]
}
