// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  TL431 — adjustable shunt voltage reference, SOT-23
//  1=REF 2=ANODE 3=CATHODE.
// =============================================================================
component REF.TL431
{
    partno = "TL431"
    package = PKG.SOT_23

    pins = [
        in 1 = REF
        io 2 = ANODE
        io 3 = CATHODE
    ]
}
