# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real watchdog supervisor (TI TPS3824, SLVS165O, April 1998 - Revised
// March 2025; detail grade TPS3824-33DBVR, 3.3V rail), transcribed from
// the page-verified sheet (tps3824.pdf in this directory; TI lit symlink
// direct hit).
// Page-verified faces: pinout Figure 5-2 + Table 5-1 p.4 -- SOT-23 (DBV)
// 5-pin, 1 RESET (active low, push-pull), 2 GND, 3 RESET (active high,
// TPS3824/3825 only), 4 WDI, 5 VDD; thresholds p.6 §6.5 (-25/-30/-33/-50
// grades -> VIT- nom 2.25/2.63/2.93/4.55 V; -33 nom 2.93 V, hysteresis
// 30mV); reset delay td 200ms, watchdog timeout 1.6s p.8; VDD 1.1V~5.5V
// p.5; IDD 15µA typ p.7; WDI floating auto-disables the watchdog (internal
// pulses, p.15; optional 1kΩ to GND defeats it); 0.1µF VDD bypass
// recommended p.7/p.16.
//
// Family-shape debt (lm66100 law, no force-binding): the mclibs SUP.WDG
// shape is VCC/GND/WDI/RESET on pads 1-4; this part carries a fifth pin
// (the active-high RESET on pad 3) and its own pad order, so it cannot
// inherit that shape (E5060). Both reset outputs still adopt the ifs RST
// face as SOURCE roles -- the first concrete SOURCE-side parts in the
// corpus (the family comment in mclibs power/sup.mc records the SOURCE
// role had zero adopters before this).
// Grade variants (-25/-30/-50) are threshold spec rows, same footprint;
// further detail grades may join as pack siblings.

use mcode.ifs

component SUP.TPS3824
{
    partno = "TPS3824-33DBVR"
    package = PKG.SOT_23_5     // TI DBV: SOT-23, 5-pin (only package offered, p.14/p.20)

    spec = [
        vdd = 1.1V ~ 5.5V, "operating range (monitors its own supply)"          // p.5
        vit = 2.93V, "reset threshold VIT- nom, -33 grade (hysteresis 30mV)"    // p.6
        td = 200ms, "reset delay after VDD > VIT- (fixed, typ)"                 // p.8
        wdt = 1.6s, "watchdog timeout tt(out) typ (retrigger on WDI falling edge)"  // p.8
        idd = 15µA, "supply current typ (WDI/MR/outputs unconnected)"           // p.7
        temp = -40°C ~ +85°C, "operating free-air temperature range"            // p.5
    ]

    pins = [
        psnk [5, 2] = [VDD, GND]::DC(1.1V~5.5V)   // supply pair, monitored rail
        out 1 = RST{RESET}::RST(SOURCE), "active-low reset output, push-pull (asserts while VDD < VIT or WDI stalls)"
        out 3 = RSTH{RESET}::RST(SOURCE), "active-high reset output (TPS3824/3825 only)"
        in 4 = WDI, "watchdog input; retrigger by falling edge within wdt; floating disables the watchdog"
    ]
}
