# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

use mclibs.digital/ttl.mc

// Abstract device-shape base (U180 ruling b3781): the verified single-gate
// D-type flip-flop shape (CLK/D/Q/_CLR + the VCC/GND power pair) is the
// binding base; the orderable package grades are variants that override
// partno/package only. The mclibs TTL.D family shape was reformed to this
// same face in b3789 (U195); the family stays a shape reference, not a
// binding target.
abstract component TTL.D.SN74LVC1G175
{
    manufacturer = "TI"
    description = "Single D-Type Flip-Flop With Asynchronous Clear"

    standard_signal_level = volt: [low: 0V ~ 0.7V, high:0.7V ~ 5.5V]

    pins = [
        in [5,2] = [VCC, GND]::DC(1.65V ~ 5.5V)

        in 1 = CLK, standard_signal_level
        in 3 = D,   standard_signal_level
        out 4 = Q,  standard_signal_level
        in 6 = _CLR, standard_signal_level
    ]

    // Standard chip-power paradigm: external supply pair into the power pins,
    // with entry decoupling hung on contact (one statement = Power+Cap)
    func Power([VCC, GND]::DC(1.65V ~ 5.5V))
    {
        [VCC, GND] -> [this.VCC, this.GND] => CAP(100nF,10V).Cap(_)
    }

    desc_features = ["Availabel in the Texas Instruments NanoFreeTM Package",
                "Supports 5-V VCC Operation",
                "Inputs Accept Voltages to 5.5V",
                "Supports Down Translation to VCC",
                "Maxtpd of 4.3ns at 3.3V",
                "Low Power Consumption, 10-μA Max ICC",
                "±24-mA Output Drive at 3.3V",
                "Ioff Supports Live Insertion, Partial-Power-Down Mode, and Back-Drive Protection",
                "Latch-Up Performance Exceeds 100 mA Per JESD 78, Class II"
                //{"ESD Protection Exceeds JESD 22", {
                // "2000-V Human-Body Model (A114-A)",
                // "200-V Machine Model (A115-A)",
                // "1000-V Charged-Device Model (C101)"}}
                ]

    desc_applications = ["TV/Set Top Box/Audio", 
                        "EPOS (Electronic Point-of-Sale)",
                        "Motor Drives",
                        "PC/Notebook",
                        "Servers",
                        "Factory Automation and Control",
                        "Tablets",
                        "Medical Healthcare and Fitness",
                        "Smart Grid",
                        "Telecom Infrastructure",
                        "Enterprise Switching",
                        "Projectors",
                        "Storage"
                    ]

    desc_overall = "This single D-type flip-flop is designed for 1.65-V to 5.5-V VCC operation.
                The SN74LVC1G175 device has an asynchronous clear (CLR) input. When CLR is high, 
                data from the input pin (D) is transferred to the output pin (Q) on the clock\"s (CLK) 
                rising edge. When CLR is low, Q is forced into the low state, regardless of the clock 
                edge or data on D.
                NanoFreeTM package technology is a major breakthrough in IC packaging concepts, using 
                the die as the package.
                This device is fully specified for partial-power-down applications using Ioff. The Ioff
                circuitry disables the outputs, preventing damaging current backflow through the device
                when it is powered down."

}

// Package grade variants: the die and the pinout are shared; the orderable
// suffix only picks the package.
component TTL.D.SN74LVC1G175_DBV : TTL.D.SN74LVC1G175
{
    partno = "SN74LVC1G175DBV"
    package = PKG.SOT_23_6
}
component TTL.D.SN74LVC1G175_DCK : TTL.D.SN74LVC1G175
{
    partno = "SN74LVC1G175DCK"
    package = PKG.SC_70_6
}
component TTL.D.SN74LVC1G175_DRY : TTL.D.SN74LVC1G175
{
    partno = "SN74LVC1G175DRY"
    package = PKG.USON6
}
component TTL.D.SN74LVC1G175_YZP : TTL.D.SN74LVC1G175
{
    partno = "SN74LVC1G175YZP"
    package = PKG.DSBGA6
}
