# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

# PCA9555

component PCA9555(partno)
{
    description = "I2C GPIO Expansion"

    if (partno == "PCA9555N")
        package = PKG.DIP24
    else if(partno == "PCA9555D")
        package = PKG.SOIC24
    else if(partno == "PCA9555DB")
        package = PKG.SSOP24
    else if(partno == "PCA9555PW")
        package = PKG.TSSOP24
    else if(partno == "PCA9555BS")
        package = PKG.HVQFN24
    else if(partno == "PCA9555HF")
        package = PKG.HWQFN24
    else
        package = PKG.DIP24

    pins = [
        psnk [24,12] = DC{VCC,GND}::DC() | [VDD, VSS]

        in [21,2,3] = A[0:2]
        io [23, 22, 1] = I2C{SDA, SCL, INTR}::I2C()

        io [4:11] = IO0{0:7}
        io [13:20] = IO1{0:7}
    ]

    func Address(address)
    {
        if (address & 0x01) RES(10kΩ).Pullup([A0, VDD]) else RES(10kΩ).Pulldown([A0, VSS])
        if (address & 0x02) RES(10kΩ).Pullup([A1, VDD]) else RES(10kΩ).Pulldown([A1, VSS])
        if (address & 0x04) RES(10kΩ).Pullup([A2, VDD]) else RES(10kΩ).Pulldown([A2, VSS])
    }
}
