# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real brushed-DC full-bridge gate driver (DRV8701P, RGE: 24-pin VQFN with
// exposed pad), transcribed from TI ZHCSDO0A (Chinese datasheet, p.3 package
// drawing; pinout page-verified, Pin Functions table cross-checked against
// the figure pin-by-pin). The P variant uses IN1/IN2 PWM control; the E
// variant (PH/EN) swaps pins 14/15 and is a different shape family. The
// ground group is pins 5 / 16 plus the unnumbered exposed pad (PPAD).
// VM operating range 5.9-45V.
// Pins ride the mclibs brushed-DC full-bridge gate driver shape.

use mclibs.motor/gatedrv.mc

component DRV8701P : GATEDRV.H1
{
    partno = "DRV8701PRGER"
}
