# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real 32Mbit SPI NOR flash (GD25Q32ESIG, SOP8), extracted from the verified
// hbl board (U192 flash batch). Pins ride the mclibs SPI NOR shape.

use mclibs.digital/flash.mc

component FLASH.GD25Q32E : FLASH.SPI_NOR
{
    partno = "GD25Q32ESIG"
}
