// Generated by MCode Bench(TM). Transcribed from the manufacturer's public
// datasheet. All datasheets, trademarks and other referenced materials are
// the property of their respective third-party owners. Provided AS IS,
// without warranty of any kind; verify against the original manufacturer
// documentation before production use.

// =============================================================================
//  PFC inductor, 150uH (symbol: winding on 3-4 plus pin 1 = core/shield pin
//  to AGND; verified against the datasheet PDF during transcription).
// =============================================================================
component IND.PFC150UH
{
    partno = "PFC-150UH"

    pins = [
        io 3 = IN
        psrc 4 = OUT
        io 1 = SHLD
    ]
}
