# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real MEMS silicon microphone (analog), extracted from the verified hbl
// board (U192, C7 electroacoustic batch). Pins ride the mclibs abstract shape.

use mclibs.audio/microphone.mc

component MICROPHONE.WM7121P : MICROPHONE.MEMS
{
    partno = "WM7121P"
    package = PKG.MIC_WM7121P
    voltage = "3.3V"                // VCC fed from the quiet VMIC rail
}
