# Generated by MCode Bench(TM). Transcribed from the manufacturer's public
# datasheet. All datasheets, trademarks and other referenced materials are
# the property of their respective third-party owners. Provided AS IS,
# without warranty of any kind; verify against the original manufacturer
# documentation before production use.

// Real dual brushed-DC H-bridge driver (DRV8833CPWP, HTSSOP-16 with PowerPAD),
// transcribed from TI SLVSCP9 (p.3 package drawing; pinout page-verified,
// Pin Functions table cross-checked against the figure pin-by-pin).
// Pin 11 is NC in the PWP; the unnumbered PowerPAD is grounded per the GND
// row description. VM operating range 2.7-11.8V.
// Pins ride the mclibs dual H-bridge shape.

use mclibs.motor/hbridge.mc

component DRV8833C : HBRIDGE.DUAL
{
    partno = "DRV8833CPWP"
}
